import assert from "node:assert/strict";
import { before, after, test } from "node:test";
import { chromium } from "playwright";
import { expect } from "@playwright/test";
import { startVisualServer } from "./setup.mjs";
import { resolveFixtureRequest } from "./fixtures.mjs";
let server;
before(async () => { server = await startVisualServer({ script: "dev" }); });
after(async () => { await server?.stop(); });
async function open(context, identity = "member", experience = false) {
  const browser = await chromium.launch({ headless: true });
  context.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1194, height: 700 }, hasTouch: true, serviceWorkers: "block" });
  await page.route("**/api/**", route => route.fulfill(resolveFixtureRequest({ pathname: new URL(route.request().url()).pathname, method: route.request().method(), identity: new URL(route.request().url()).searchParams.get("experience") === "1" ? "guest" : identity, scenarioId: "reader-controls-narrow", cookie: route.request().headers().cookie ?? "" })));
  await page.addInitScript(() => localStorage.setItem("reader-gesture-hint-seen", "true"));
  await page.goto(`${server.origin}/choirs/visual-choir/scores/visual-score${experience ? "?experience=1" : ""}`);
  await page.locator('.page-reader__sheet[data-page-turn-current] canvas[data-pdf-canvas-active]').waitFor();
  await page.locator('.page-reader__viewport').click({ position: { x: 590, y: 350 } });
  await page.getByRole('button', { name: '更多', exact: true }).click();
  return page;
}
test('landscape continuous fit contains the entire current page', async context => {
  const page = await open(context);
  await page.getByRole('button', { name: '连续滚动', exact: true }).click();
  await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '适合页面', exact: true }).click();
  await expect.poll(() => page.locator('.continuous-reader__page[data-index="0"] .annotated-pdf-page').evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(700);
});
test('safe areas do not cut off the zoomed landscape viewport', async context => {
  const page = await open(context);
  await page.evaluate(() => document.querySelector('.reader-shell').style.cssText = '--reader-safe-left: 24px; --reader-safe-right: 24px; --reader-safe-bottom: 20px');
  await page.getByRole('button', { name: '放大', exact: true }).click();
  const bounds = await page.locator('.page-reader__viewport').boundingBox();
  assert.equal(bounds.x, 0);
  assert.equal(bounds.width, 1194);
  assert.equal(bounds.height, 700);
});
test('two-finger editing pans the score without leaving a text placement', async context => {
  const page = await open(context);
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: '放大', exact: true }).click();
  await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.locator('.annotation-controls').waitFor();
  const reader = page.locator('.page-reader__viewport');
  await reader.evaluate(el => el.scrollTop = 150);
  const cdp = await page.context().newCDPSession(page);
  const send = (type, points) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([x, y, id]) => ({ x, y, id })) });
  await send('touchStart', [[500, 350, 1]]);
  await send('touchStart', [[500, 350, 1], [650, 350, 2]]);
  await send('touchMove', [[500, 300, 1], [650, 300, 2]]);
  await send('touchEnd', []);
  await expect.poll(() => reader.evaluate(el => el.scrollTop)).toBe(200);
  assert.equal(await page.getByRole('textbox', { name: '笔记文本' }).count(), 0);
  assert.equal(await page.locator('.page-reader__sheet[data-page-turn-current]').getAttribute('data-page-number'), '1');
});
test('guest edits survive reload without any annotation mutation request', async context => {
  const page = await open(context, 'guest');
  const mutations = [];
  page.on('request', request => { if (new URL(request.url()).pathname.includes('/api/') && !['GET', 'HEAD'].includes(request.method())) mutations.push(request.url()); });
  await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.locator('.annotation-controls').waitFor();
  await page.getByLabel('第 1 页笔记层').click({ position: { x: 200, y: 250 } });
  await page.getByRole('textbox', { name: '笔记文本' }).fill('本机试写');
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  await page.reload();
  await page.locator('.annotation-text').filter({ hasText: '本机试写' }).waitFor();
  assert.deepEqual(mutations, []);
});

test('signed-in experience stays local and does not upload notes', async context => {
  const page = await open(context, 'member', true);
  const mutations = [];
  page.on('request', request => { if (new URL(request.url()).pathname.includes('/api/') && !['GET', 'HEAD'].includes(request.method())) mutations.push(request.url()); });
  await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.locator('.annotation-controls').waitFor();
  await page.getByLabel('第 1 页笔记层').click({ position: { x: 200, y: 250 } });
  await page.getByRole('textbox', { name: '笔记文本' }).fill('登录后的体验');
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  await page.reload();
  await page.locator('.annotation-text').filter({ hasText: '登录后的体验' }).waitFor();
  assert.deepEqual(mutations, []);
  await page.goto(`${server.origin}/choirs/visual-choir/scores/visual-score`);
  await page.locator('.page-reader__sheet[data-page-turn-current] canvas[data-pdf-canvas-active]').waitFor();
  assert.equal(await page.locator('.annotation-text').filter({ hasText: '登录后的体验' }).count(), 0);
});
test('fullscreen includes the text portal and exits on leaving the reader', async context => {
  const page = await open(context);
  await page.getByRole('button', { name: '全屏阅读', exact: true }).click();
  await expect.poll(() => page.evaluate(() => document.fullscreenElement === document.documentElement)).toBe(true);
  await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.locator('.annotation-controls').waitFor();
  await page.getByLabel('第 1 页笔记层').click({ position: { x: 200, y: 250 } });
  await expect(page.getByRole('textbox', { name: '笔记文本' })).toBeFocused();
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  await page.getByRole('button', { name: '返回云盘', exact: true }).click();
  await expect.poll(() => page.evaluate(() => document.fullscreenElement)).toBe(null);
});
test('fitting the second continuous page keeps that page selected after rotation', async context => {
  const page = await open(context);
  await page.getByRole('button', { name: '连续滚动', exact: true }).click();
  await page.getByRole('slider', { name: '跳转页码' }).press('End');
  await expect(page.getByRole('slider', { name: '跳转页码' })).toHaveValue('2');
  await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '适合页面', exact: true }).click();
  const paper = page.locator('.continuous-reader__page[data-index="1"] .annotated-pdf-page');
  await expect.poll(() => paper.evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(700);
  await expect.poll(() => paper.evaluate(el => Math.abs(el.getBoundingClientRect().top))).toBeLessThan(2);
  await page.setViewportSize({ width: 700, height: 1194 });
  await expect.poll(() => paper.evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(1194);
  await expect(page.getByRole('slider', { name: '跳转页码' })).toHaveValue('2');
});
for (const layout of ['page', 'continuous']) test(`${layout}: two fingers cancel an ink checkpoint instead of saving an accidental stroke`, async context => {
  const page = await open(context, 'guest');
  if (layout === 'continuous') await page.getByRole('button', { name: '连续滚动', exact: true }).click();
  else await page.getByRole('button', { name: '更多', exact: true }).click();
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.getByRole('button', { name: '画笔', exact: true }).click();
  const cdp = await page.context().newCDPSession(page);
  const send = (type, points) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([x, y, id]) => ({ x, y, id })) });
  await send('touchStart', [[500, 300, 1]]);
  await send('touchMove', [[520, 310, 1]]);
  await expect.poll(() => page.locator('[data-ink-draft]').count()).toBeGreaterThan(0);
  await expect.poll(() => page.evaluate(async () => {
    const { localDatabase } = await import('/src/client/platform/local-database.ts');
    return localDatabase.annotations.filter(note => note.payload?.kind === 'ink' && !note.deleted).count();
  })).toBeGreaterThan(0);
  await send('touchStart', [[520, 310, 1], [650, 310, 2]]);
  await send('touchMove', [[520, 290, 1], [650, 290, 2]]);
  await send('touchEnd', []);
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  await page.reload();
  await page.locator(layout === 'page' ? '.page-reader__sheet[data-page-turn-current] canvas[data-pdf-canvas-active]' : '.continuous-reader__page[data-index="0"] canvas[data-pdf-canvas-active]').waitFor();
  assert.equal(await page.locator('[data-ink-stroke]').count(), 0);
});
