import { mkdir } from "node:fs/promises";
import { test } from "node:test";
import { chromium, webkit, expect } from "@playwright/test";
import { startVisualServer } from "./setup.mjs";
import { createVisualFixtureSession } from "./fixtures.mjs";

for (const [name, engine] of [["chromium", chromium], ["webkit", webkit]]) {
  test(`${name}: drawer and reader settings return to their source, and changed forms require a decision`, async t => {
    const app = await startVisualServer({ script: "dev" });
    const browser = await engine.launch();
    t.after(async () => { await browser.close(); await app.stop(); });
    const page = await browser.newPage({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
    page.setDefaultTimeout(12000);
    const fixture = createVisualFixtureSession({ id: "uiux-return", identity: "admin" });
    await page.route("**/api/**", route => {
      const request = route.request();
      const pathname = new URL(request.url()).pathname;
      const result = fixture.resolve({ pathname, method: request.method(), identity: "admin", cookie: "", body: request.headers()["content-type"]?.includes("application/json") ? request.postDataJSON() : null });
      if (pathname.endsWith("/memberships") && request.method() === "GET") {
        const data = JSON.parse(result.body);
        data.memberships.push(...Array.from({ length: 98 }, (_, i) => ({ ...data.memberships[1], id: `member-${i}`, displayName: `排练成员${i}`, status: i === 97 ? "removed" : "active" })));
        result.body = JSON.stringify(data);
      }
      return route.fulfill(result);
    });
    await page.addInitScript(() => localStorage.setItem("reader-gesture-hint-seen", "true"));
    const drive = `${app.origin}/choirs/visual-choir`;
    await page.goto(drive);
    await page.getByRole("searchbox").fill("排练");
    await expect(page.locator(".drive-header__identity > strong")).toBeVisible();
    await page.getByRole("button", { name: "打开云盘菜单" }).click();
    await page.getByRole("link", { name: "成员与权限", exact: true }).click();
    await expect(page.getByRole("heading", { name: "成员与权限" })).toBeVisible();
    await expect(page.locator(".brand-link")).toHaveCount(0);
    await expect(page.getByRole("heading", { name: "排练成员97", exact: true })).toHaveCount(0);
    await page.getByRole("combobox", { name: "成员状态" }).selectOption("removed");
    await expect(page.getByRole("heading", { name: "排练成员97", exact: true })).toBeVisible();
    await page.getByRole("combobox", { name: "成员状态" }).selectOption("active");
    await page.getByRole("searchbox", { name: "搜索成员" }).fill("周宁");
    await expect(page.getByRole("heading", { name: "周宁" })).toBeVisible();
    await expect(page.getByRole("heading", { name: /林老师/ })).toHaveCount(0);
    await page.getByRole("heading", { name: "周宁", exact: true }).click();
    await page.getByText("编辑权限", { exact: true }).click();
    await page.getByRole("checkbox", { name: "上传文件：可以操作", exact: true }).click();
    const cancelPermission = page.getByRole("button", { name: "取消修改", exact: true });
    await expect(cancelPermission).toBeVisible();
    expect((await cancelPermission.boundingBox()).height).toBeGreaterThanOrEqual(44);
    await cancelPermission.click();
    await expect(cancelPermission).toHaveCount(0);
    await page.getByRole("button", { name: "返回", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "云盘菜单" })).toBeVisible();
    await expect(page.getByRole("link", { name: "成员与权限", exact: true })).toBeFocused();
    await page.getByRole("link", { name: "帮助", exact: true }).click();
    await expect(page.getByRole("heading", { name: "帮助", exact: true })).toBeVisible();
    await page.goBack();
    await expect(page.getByRole("dialog", { name: "云盘菜单" })).toBeVisible();
    await page.getByRole("button", { name: "关闭云盘菜单" }).click();
    await expect(page.getByRole("button", { name: "打开云盘菜单" })).toBeFocused();
    await expect(page.getByRole("searchbox")).toHaveValue("排练");
    await page.goto(`${drive}/shared-layers/E`);
    await page.getByRole("textbox", { name: "名称", exact: true }).fill("新的排练提醒");
    await page.getByRole("button", { name: "返回", exact: true }).click();
    await page.getByRole("button", { name: "继续编辑", exact: true }).click();
    await expect(page.getByRole("textbox", { name: "名称", exact: true })).toHaveValue("新的排练提醒");
    await page.getByRole("button", { name: "返回", exact: true }).click();
    await page.getByRole("button", { name: "放弃修改", exact: true }).click();
    await expect(page.getByRole("heading", { name: "共享层", exact: true })).toBeVisible();
    await page.getByRole("link", { name: /Ensemble/ }).click();
    await page.getByRole("textbox", { name: "名称", exact: true }).fill("已确认的排练提醒");
    await page.getByRole("button", { name: "返回", exact: true }).click();
    await page.getByRole("button", { name: "保存并返回", exact: true }).click();
    await expect(page.getByRole("heading", { name: "共享层", exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: /已确认的排练提醒/ })).toBeVisible();
    await page.goto(`${drive}/scores/visual-score`);
    await page.locator("canvas[data-pdf-canvas-active]").first().waitFor();
    await page.locator(".page-reader__viewport").click();
    await page.getByRole("button", { name: "更多", exact: true }).click();
    await page.getByRole("button", { name: "放大", exact: true }).click();
    await page.keyboard.press("Escape");
    await page.getByRole("button", { name: "看哪些笔记", exact: true }).click();
    await page.getByRole("link", { name: "设置此云盘的默认显示" }).click();
    await expect(page.getByRole("heading", { name: "阅读偏好", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "返回", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "看哪些笔记" })).toBeVisible();
    await expect(page.locator(".page-reader__viewport")).toHaveAttribute("data-zoom", "1.25");
    await mkdir("artifacts/verification/issue-216", { recursive: true });
    await page.screenshot({ path: `artifacts/verification/issue-216/${name}-reader-return.png` });
    await page.getByRole("button", { name: "关闭笔记显示" }).click();
    await expect(page.getByRole("button", { name: "看哪些笔记", exact: true })).toBeFocused();
    await page.evaluate(() => history.replaceState({ ...history.state, usr: { ...history.state.usr, readerReturnPanel: "layers" } }, ""));
    await page.reload();
    await page.locator("canvas[data-pdf-canvas-active]").first().waitFor();
    await expect(page.getByRole("dialog", { name: "看哪些笔记" })).toHaveCount(0);
    await page.goto(`${app.origin}/help`);
    await page.getByRole("button", { name: "返回", exact: true }).click();
    await expect(page.getByRole("heading", { name: "我已加入的云盘" })).toBeVisible();
    await expect(page.getByRole("dialog")).toHaveCount(0);
  });
}
