import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import test from "node:test";
import { chromium, expect } from "@playwright/test";
import { startStorageFixture } from "./storage-fixture.mjs";

test("real Worker: create trial, upload, permanently clear trash and close drive", {timeout:90_000}, async t => {
  const fixture=await startStorageFixture({authenticated:true,previewEntry:false});
  t.after(()=>fixture.stop());
  const browser=await chromium.launch();t.after(()=>browser.close());
  const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:"block"});
  const account=fixture.accounts[0];
  const login=await context.request.post(`${fixture.origin}/api/auth/sign-in/email`,{headers:{origin:fixture.origin},data:{email:account.email,password:account.password}});
  assert.equal(login.status(),200);
  const page=await context.newPage();
  await page.goto(`${fixture.origin}/drives`);
  await page.getByRole("button",{name:"创建云盘",exact:true}).click();
  await page.getByLabel("云盘名称",{exact:true}).fill("周末排练");
  await page.getByLabel("你在云盘内的显示名").fill("指挥");
  await mkdir("artifacts/verification/free-trial",{recursive:true});
  await page.screenshot({path:"artifacts/verification/free-trial/create-mobile.png"});
  await page.getByRole("button",{name:"免费创建",exact:true}).click();
  await expect(page.getByRole("heading",{name:"周末排练",exact:true})).toBeVisible();
  const driveId=new URL(page.url()).pathname.split("/")[2];
  await page.getByRole("button",{name:"上传第一份 PDF",exact:true}).click();
  await page.getByLabel("选择 PDF 文件").setInputFiles({name:"试用乐谱.pdf",mimeType:"application/pdf",buffer:fixture.pdf});
  await expect(page.locator(".upload-list li[data-status='success']")).toHaveCount(1);
  await page.getByRole("button",{name:"关闭",exact:true}).click();
  const list=await (await context.request.get(`${fixture.origin}/api/choirs/${driveId}/scores`)).json();
  assert.equal(list.scores.length,1);
  const scoreId=list.scores[0].id;
  assert.equal((await context.request.delete(`${fixture.origin}/api/choirs/${driveId}/scores/${scoreId}`,{headers:{origin:fixture.origin}})).status(),204);
  await page.goto(`${fixture.origin}/choirs/${driveId}/settings/trash`);
  await page.getByRole("button",{name:"彻底删除",exact:true}).click();
  await expect(page.getByRole("alertdialog")).toContainText("所有成员的笔记");
  await page.screenshot({path:"artifacts/verification/free-trial/purge-mobile.png"});
  await page.getByRole("button",{name:"确认彻底删除",exact:true}).click();
  await expect(page.getByText("回收站是空的。",{exact:true})).toBeVisible();
  assert.equal((await context.request.get(`${fixture.origin}/api/choirs/${driveId}/scores/${scoreId}/pdf`)).status(),404);
  await page.goto(`${fixture.origin}/choirs/${driveId}/settings/info`);
  await expect(page.getByRole("heading",{name:"免费体验版",exact:true})).toBeVisible();
  await expect(page.getByText(/乐谱 0\/10.*成员 1\/20/)).toBeVisible();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:"artifacts/verification/free-trial/usage-mobile.png"});
  await page.getByRole("button",{name:"彻底删除云盘",exact:true}).click();
  await page.getByLabel("输入云盘名称“周末排练”确认").fill("周末排练");
  await page.getByRole("button",{name:"确认彻底删除",exact:true}).click();
  await expect(page).toHaveURL(`${fixture.origin}/drives`);
  assert.equal((await context.request.get(`${fixture.origin}/api/choirs/${driveId}/bootstrap`)).status(),404);
});
